"""message

Revision ID: bda1f98cbe6d
Revises: c2f28f68c9d3
Create Date: 2024-06-30 21:56:00.079028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda1f98cbe6d'
down_revision = 'c2f28f68c9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
