"""message

Revision ID: c2f28f68c9d3
Revises: 957bc0d74a91
Create Date: 2024-06-30 21:39:52.765097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f28f68c9d3'
down_revision = '957bc0d74a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
