"""message

Revision ID: c3b709c42aae
Revises: bda1f98cbe6d
Create Date: 2024-06-30 22:04:47.054205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b709c42aae'
down_revision = 'bda1f98cbe6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
